[tool.black]
# Black configuration for Jupyter notebooks
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$|\.ipynb$'
extend-exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
  | \.egg-info
)/
'''

[tool.pylint]
# Pylint configuration for notebooks

[tool.pylint.messages_control]
# Disable notebook-specific warnings
disable = [
    "C0114",  # missing-module-docstring
    "C0116",  # missing-function-docstring  
    "C0103",  # invalid-name (common in notebooks for short variable names)
    "W0613",  # unused-argument
    "R0903",  # too-few-public-methods
    "R0913",  # too-many-arguments
    "R0914",  # too-many-locals
    "R0915",  # too-many-statements
    "C0301",  # line-too-long (handled by black)
    "W0611",  # unused-import (common in notebooks)
    "E1101",  # no-member (often false positives with dynamic imports)
    "E0602",  # undefined-variable (for JSON null values in notebooks)
    "W0104",  # pointless-statement (JSON structure in notebooks)
    "C0302",  # too-many-lines (notebooks can be long)
]

[tool.pylint.format]
max-line-length = 88

[tool.isort]
# isort configuration to work with Black
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true